//! How a Cloud Hypervisor VM's processes are started and stopped.
//!
//! Each VM is one `launch.sh` in its directory: it starts one virtiofsd per
//! shared directory, waits for their sockets, and execs cloud-hypervisor.
//! Generated rather than assembled in Rust so an operator can read exactly
//! what ran, and re-run it by hand.
//!
//! Under systemd the script runs as a transient unit in `puku-vms.slice`:
//! its own cgroup, so the VM outlives a workerd restart (workerd's unit
//! stops only workerd) and gets a memory ceiling. Elsewhere it runs as its
//! own session, which also outlives workerd.

use std::path::{Path, PathBuf};

use super::net::NetSlot;

/// Everything the launcher needs, resolved to paths.
#[derive(Debug, Clone)]
pub struct Launch {
    pub name: String,
    pub dir: PathBuf,
    pub ch_bin: PathBuf,
    pub virtiofsd_bin: PathBuf,
    pub kernel: PathBuf,
    pub rootfs: PathBuf,
    /// The writable disk overlaid on `rootfs`: a fresh one per VM, or a
    /// machine's persistent root.
    pub upper: PathBuf,
    pub cpus: u8,
    pub memory_mib: u32,
    /// (tag, host dir, guest path)
    pub shares: Vec<(String, PathBuf, String)>,
    pub net: NetSlot,
    pub max_duration_s: Option<u64>,
    /// Size of the guest's /dev/shm.
    pub shm: String,
    /// Hand memory the guest frees back to the host (virtio-balloon free
    /// page reporting).
    pub free_page_reporting: bool,
}

/// The cgroup ceiling for a VM of this size: the guest, the VMM and
/// virtiofsd. With `shared=on` the guest's touched RAM is shmem the host
/// cannot reclaim, so the margin grows with the guest.
pub fn memory_max_mib(memory_mib: u32) -> u64 {
    memory_mib as u64 + 512 + memory_mib as u64 / 32
}

fn q(s: &str) -> String {
    // Single-quote for sh; paths here are ours, but a quote in one must not
    // become a command.
    format!("'{}'", s.replace('\'', "'\\''"))
}

fn qp(p: &Path) -> String {
    q(&p.display().to_string())
}

impl Launch {
    pub fn unit(&self) -> String {
        format!("puku-vm-{}", self.name)
    }

    pub fn socket(&self, file: &str) -> PathBuf {
        self.dir.join(file)
    }

    /// The kernel command line. Nothing secret: credentials go over vsock.
    pub fn cmdline(&self) -> String {
        let fs = self
            .shares
            .iter()
            .map(|(tag, _, guest)| format!("{tag}:{guest}"))
            .collect::<Vec<_>>()
            .join(",");
        let mut c = format!(
            "console=hvc0 root=/dev/vda ro rootfstype=ext4 init=/sbin/puku-guestd panic=-1 \
             puku.overlay=/dev/vdb puku.ip={}/30 puku.gw={} puku.dns={} puku.hostname={} puku.shm={}",
            self.net.guest, self.net.host, self.net.host, self.name, self.shm
        );
        if !fs.is_empty() {
            c.push_str(&format!(" puku.fs={fs}"));
        }
        c
    }

    pub fn script(&self) -> String {
        let mut s = String::from("#!/bin/sh\n# Generated by puku-workerd. Starts this VM's virtiofsd(s), then cloud-hypervisor.\nset -eu\n");
        s.push_str(&format!("cd {}\n", qp(&self.dir)));
        let mut sockets = Vec::new();
        for (tag, host, _) in &self.shares {
            let sock = self.socket(&format!("{tag}.sock"));
            s.push_str(&format!(
                "{} --socket-path={} --shared-dir={} --cache=auto --sandbox=namespace --xattr >> virtiofsd-{tag}.log 2>&1 &\n",
                qp(&self.virtiofsd_bin),
                qp(&sock),
                qp(host),
            ));
            sockets.push(sock);
        }
        for sock in &sockets {
            s.push_str(&format!(
                "i=0; while [ ! -S {} ] && [ $i -lt 200 ]; do sleep 0.05; i=$((i+1)); done\n",
                qp(sock)
            ));
        }
        let mut ch = vec![
            qp(&self.ch_bin),
            "--api-socket".into(),
            format!("path={}", qp(&self.socket("api.sock"))),
            "--kernel".into(),
            qp(&self.kernel),
            "--cmdline".into(),
            q(&self.cmdline()),
            "--cpus".into(),
            format!("boot={}", self.cpus.max(1)),
            // shared=on: virtiofs maps guest memory, which it can only do
            // when that memory is shareable.
            "--memory".into(),
            format!("size={}M,shared=on", self.memory_mib),
            "--disk".into(),
            // image_type=raw: without it Cloud Hypervisor v53.0+ autodetects
            // raw and silently rejects writes to sector 0. ext4 keeps its
            // superblock at sector 0, so a writable upper disk with no
            // explicit type fails the overlay mount with an I/O error.
            format!("path={},readonly=on,image_type=raw", qp(&self.rootfs)),
            format!("path={},image_type=raw", qp(&self.upper)),
            "--net".into(),
            format!("tap={},mac={}", self.net.tap, self.net.mac),
            "--vsock".into(),
            format!("cid={},socket={}", self.net.cid, qp(&self.socket("vsock.sock"))),
            // Without an entropy source the guest can stall at boot waiting
            // for enough of it to start TLS.
            "--rng".into(),
            "src=/dev/urandom".into(),
            "--console".into(),
            format!("file={}", qp(&self.socket("console.log"))),
            "--serial".into(),
            "off".into(),
        ];
        if self.free_page_reporting {
            // A balloon of size 0 that never inflates. It is there to carry
            // free page reporting, so memory the guest frees goes back to the
            // host instead of staying pinned for the life of the VM.
            ch.push("--balloon".into());
            ch.push("size=0,free_page_reporting=on".into());
        }
        if !self.shares.is_empty() {
            ch.push("--fs".into());
            for (tag, _, _) in &self.shares {
                ch.push(format!("tag={tag},socket={}", qp(&self.socket(&format!("{tag}.sock")))));
            }
        }
        let prefix = match self.max_duration_s {
            // The wall-clock cap msb enforced with its own timer.
            Some(secs) if secs > 0 => format!("exec timeout --signal=TERM --kill-after=15 {secs} "),
            _ => "exec ".into(),
        };
        s.push_str(&prefix);
        s.push_str(&ch.join(" \\\n  "));
        s.push('\n');
        s
    }

    /// The transient-unit invocation, for hosts running systemd.
    pub fn systemd_run_args(&self) -> Vec<String> {
        let mut a = vec![
            format!("--unit={}", self.unit()),
            "--slice=puku-vms.slice".into(),
            "--collect".into(),
            "--quiet".into(),
            "--property=KillMode=control-group".into(),
            "--property=TasksMax=4096".into(),
            // A flat 256 MiB on top was fine for a 2 GiB session and an OOM
            // kill waiting to happen for a 16 GiB desktop.
            format!("--property=MemoryMax={}M", memory_max_mib(self.memory_mib)),
            format!("--property=StandardOutput=append:{}", self.socket("launch.log").display()),
            format!("--property=StandardError=append:{}", self.socket("launch.log").display()),
        ];
        a.push("/bin/sh".into());
        a.push(self.socket("launch.sh").display().to_string());
        a
    }
}

pub fn has_systemd() -> bool {
    Path::new("/run/systemd/system").exists() && which("systemd-run").is_some()
}

pub fn which(bin: &str) -> Option<PathBuf> {
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths).map(|p| p.join(bin)).find(|p| p.is_file())
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn launch() -> Launch {
        Launch {
            name: "ses-abc".into(),
            dir: "/var/lib/puku/vms/ses-abc".into(),
            ch_bin: "/opt/puku/ch/bin/cloud-hypervisor".into(),
            virtiofsd_bin: "/opt/puku/ch/bin/virtiofsd".into(),
            kernel: "/opt/puku/ch/vmlinux".into(),
            rootfs: "/var/lib/puku/images/puku-agent/rootfs.ext4".into(),
            upper: "/var/lib/puku/vms/ses-abc/upper.ext4".into(),
            cpus: 2,
            memory_mib: 2048,
            shares: vec![
                ("fs0".into(), "/var/lib/puku/sessions/x/session".into(), "/session".into()),
                ("fs1".into(), "/var/lib/puku/sessions/x/workspace".into(), "/workspace".into()),
            ],
            net: NetSlot::new(3),
            max_duration_s: Some(14_400),
            shm: "512m".into(),
            free_page_reporting: false,
        }
    }

    #[test]
    fn the_memory_ceiling_grows_with_the_guest() {
        assert_eq!(memory_max_mib(2048), 2048 + 512 + 64);
        assert_eq!(memory_max_mib(16384), 16384 + 512 + 512);
        let unit = launch().systemd_run_args().join(" ");
        assert!(unit.contains(&format!("MemoryMax={}M", memory_max_mib(2048))), "{unit}");
    }

    #[test]
    fn free_page_reporting_is_opt_in() {
        assert!(!launch().script().contains("--balloon"));
        let l = Launch { free_page_reporting: true, ..launch() };
        assert!(l.script().contains("--balloon \\\n  size=0,free_page_reporting=on"), "{}", l.script());
    }

    #[test]
    fn the_command_line_carries_layout_not_secrets() {
        let c = launch().cmdline();
        assert!(c.contains("init=/sbin/puku-guestd"));
        assert!(c.contains("puku.overlay=/dev/vdb"));
        assert!(c.contains("puku.fs=fs0:/session,fs1:/workspace"));
        assert!(c.contains("puku.ip=10.200.0.14/30 puku.gw=10.200.0.13"));
        assert!(c.contains("console=hvc0"));
    }

    #[test]
    fn the_script_starts_one_virtiofsd_per_share_then_the_vmm() {
        let s = launch().script();
        assert_eq!(s.matches("--shared-dir=").count(), 2);
        assert!(s.contains("--memory \\\n  size=2048M,shared=on"), "virtiofs needs shared memory: {s}");
        assert!(s.contains("path='/var/lib/puku/images/puku-agent/rootfs.ext4',readonly=on,image_type=raw"));
        assert!(s.contains("upper.ext4"));
        assert!(s.contains("tap=pkt3,mac="));
        assert!(s.contains("cid=5,socket="));
        assert!(s.contains("--rng"));
        assert!(s.contains("tag=fs0,socket="));
        assert!(s.contains("exec timeout --signal=TERM --kill-after=15 14400"), "{s}");
        // virtiofsd must be up before the VMM connects to it.
        assert!(s.find("--shared-dir").unwrap() < s.find("while [ ! -S").unwrap());
        assert!(s.find("while [ ! -S").unwrap() < s.find("cloud-hypervisor'").unwrap());
    }

    #[test]
    fn a_quote_in_a_path_cannot_become_a_command() {
        assert_eq!(q("a'b"), "'a'\\''b'");
    }

    #[test]
    fn the_unit_is_its_own_cgroup_in_the_vm_slice() {
        let a = launch().systemd_run_args();
        assert!(a.contains(&"--unit=puku-vm-ses-abc".to_string()));
        assert!(a.contains(&"--slice=puku-vms.slice".to_string()));
        assert!(a.contains(&format!("--property=MemoryMax={}M", memory_max_mib(2048))), "{a:?}");
        assert_eq!(a.last().unwrap(), "/var/lib/puku/vms/ses-abc/launch.sh");
    }

    #[test]
    fn no_cap_means_plain_exec() {
        let mut l = launch();
        l.max_duration_s = None;
        l.shares.clear();
        let s = l.script();
        assert!(s.contains("exec '/opt/puku/ch/bin/cloud-hypervisor'"));
        assert!(!s.contains("--fs"));
    }
}
