//! `puku-rebuild`: emit a shell script that replays `installed_packages`
//! against a fresh base image.
//!
//! Per docs/RELIABILITY-REBUILD.md §4.6. Recovers the *environment*, not
//! data files.

use std::collections::BTreeMap;

use chrono::{DateTime, Utc};
use clap::Parser;
use uuid::Uuid;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum PackageKind {
    Apt,
    Pip,
    Npm,
    Cargo,
    Go,
    Gem,
    Brew,
    System,
}

impl PackageKind {
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "apt" => Some(Self::Apt),
            "pip" => Some(Self::Pip),
            "npm" => Some(Self::Npm),
            "cargo" => Some(Self::Cargo),
            "go" => Some(Self::Go),
            "gem" => Some(Self::Gem),
            "brew" => Some(Self::Brew),
            "system" => Some(Self::System),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Apt => "apt",
            Self::Pip => "pip",
            Self::Npm => "npm",
            Self::Cargo => "cargo",
            Self::Go => "go",
            Self::Gem => "gem",
            Self::Brew => "brew",
            Self::System => "system",
        }
    }
}

#[derive(Debug, Clone)]
pub struct InstalledPackage {
    pub kind: PackageKind,
    pub name: String,
    pub version: Option<String>,
    pub ts: DateTime<Utc>,
}

/// In-memory source for tests; production wires a Postgres reader.
pub trait PackageSource: Send + Sync {
    fn list(&self, session_id: Uuid) -> Result<Vec<InstalledPackage>, String>;
}

pub struct InMemoryPackages {
    pub by_session: std::collections::HashMap<Uuid, Vec<InstalledPackage>>,
}

impl InMemoryPackages {
    pub fn new() -> Self {
        Self {
            by_session: std::collections::HashMap::new(),
        }
    }
    pub fn with(mut self, sid: Uuid, pkgs: Vec<InstalledPackage>) -> Self {
        self.by_session.insert(sid, pkgs);
        self
    }
}
impl Default for InMemoryPackages {
    fn default() -> Self {
        Self::new()
    }
}
impl PackageSource for InMemoryPackages {
    fn list(&self, session_id: Uuid) -> Result<Vec<InstalledPackage>, String> {
        Ok(self.by_session.get(&session_id).cloned().unwrap_or_default())
    }
}

#[derive(Debug, Parser)]
#[command(name = "puku-rebuild", about = "Emit env-rebuild shell script")]
struct Args {
    /// Session id whose packages to replay.
    session: Uuid,
    /// Output file; defaults to stdout.
    #[arg(short, long)]
    output: Option<std::path::PathBuf>,
}

/// Build the script as a String. The order is: apt first (foundation),
/// then pip/npm/cargo in install order (BTreeMap by ts).
pub fn build_script(session_id: Uuid, pkgs: Vec<InstalledPackage>) -> String {
    // Group by kind.
    let mut by_kind: BTreeMap<PackageKind, Vec<&InstalledPackage>> = BTreeMap::new();
    for p in &pkgs {
        by_kind.entry(p.kind).or_default().push(p);
    }
    // Within a kind, sort by ts so the replay is in install order.
    for v in by_kind.values_mut() {
        v.sort_by_key(|p| p.ts);
    }

    let mut s = String::new();
    s.push_str("#!/bin/sh\n");
    s.push_str(&format!(
        "# Auto-generated by puku-rebuild from installed_packages for session {}\n",
        session_id
    ));
    s.push_str("set -e\n\n");

    // Apt: prerequisites.
    s.push_str("apt-get update\n");
    s.push_str("apt-get install -y --no-install-recommends \\\n");
    s.push_str("    git curl wget ca-certificates\n\n");

    // Apt packages.
    if let Some(apts) = by_kind.get(&PackageKind::Apt) {
        if !apts.is_empty() {
            s.push_str("# apt\n");
            s.push_str("apt-get install -y --no-install-recommends \\\n");
            for (i, p) in apts.iter().enumerate() {
                let suffix = if i + 1 == apts.len() { "" } else { " \\\n" };
                let line = match &p.version {
                    Some(v) => format!("    {}={}{}", p.name, v, suffix),
                    None => format!("    {}{}", p.name, suffix),
                };
                s.push_str(&line);
            }
            s.push('\n');
        }
    }
    // Pip
    if let Some(pips) = by_kind.get(&PackageKind::Pip) {
        if !pips.is_empty() {
            s.push_str("\n# pip\n");
            s.push_str("pip install --no-cache-dir \\\n");
            for (i, p) in pips.iter().enumerate() {
                let suffix = if i + 1 == pips.len() { "" } else { " \\\n" };
                let line = match &p.version {
                    Some(v) => format!("    {}=={}{}", p.name, v, suffix),
                    None => format!("    {}{}", p.name, suffix),
                };
                s.push_str(&line);
            }
            s.push('\n');
        }
    }
    // npm
    if let Some(npm) = by_kind.get(&PackageKind::Npm) {
        if !npm.is_empty() {
            s.push_str("\n# npm\n");
            for p in npm {
                match &p.version {
                    Some(v) => s.push_str(&format!("npm install -g {}@{}\n", p.name, v)),
                    None => s.push_str(&format!("npm install -g {}\n", p.name)),
                }
            }
        }
    }
    // cargo / go / gem / brew: best-effort installers
    for kind in [PackageKind::Cargo, PackageKind::Go, PackageKind::Gem, PackageKind::Brew] {
        if let Some(v) = by_kind.get(&kind) {
            if !v.is_empty() {
                s.push_str(&format!("\n# {}\n", kind.as_str()));
                let installer = match kind {
                    PackageKind::Cargo => "cargo install",
                    PackageKind::Go => "go install",
                    PackageKind::Gem => "gem install",
                    PackageKind::Brew => "brew install",
                    _ => unreachable!(),
                };
                for p in v {
                    let arg = match &p.version {
                        Some(ver) => format!("{}@{}", p.name, ver),
                        None => p.name.clone(),
                    };
                    s.push_str(&format!("{} {}\n", installer, arg));
                }
            }
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn pkg(kind: PackageKind, name: &str, version: Option<&str>, ts: i64) -> InstalledPackage {
        InstalledPackage {
            kind,
            name: name.into(),
            version: version.map(String::from),
            ts: Utc.timestamp_opt(ts, 0).unwrap(),
        }
    }

    #[test]
    fn script_lists_apt_and_pip() {
        let s = Uuid::new_v4();
        let pkgs = vec![
            pkg(PackageKind::Apt, "jq", Some("1.7"), 100),
            pkg(PackageKind::Pip, "requests", Some("2.31.0"), 200),
            pkg(PackageKind::Apt, "git", None, 300),
        ];
        let script = build_script(s, pkgs);
        assert!(script.contains("apt-get install"));
        assert!(script.contains("jq=1.7"));
        assert!(script.contains("pip install"));
        assert!(script.contains("requests==2.31.0"));
        assert!(!script.contains("wrgl"));
    }

    #[test]
    fn script_orders_within_kind_by_ts() {
        let s = Uuid::new_v4();
        let pkgs = vec![
            pkg(PackageKind::Pip, "newer", None, 200),
            pkg(PackageKind::Pip, "older", None, 100),
        ];
        let script = build_script(s, pkgs);
        let older_pos = script.find("older").unwrap();
        let newer_pos = script.find("newer").unwrap();
        assert!(older_pos < newer_pos, "older must come before newer");
    }

    #[test]
    fn empty_packages_still_runs_foundation() {
        let s = Uuid::new_v4();
        let script = build_script(s, vec![]);
        assert!(script.contains("apt-get update"));
        assert!(script.contains("git"));
        assert!(!script.contains("pip install"));
        assert!(!script.contains("npm install"));
    }
}
